-- VFS StudioFlow: Activity / Update History
-- Creates a database-backed audit trail for works, work notes, and staff profiles.
-- No service-role key is used in the browser.

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  actor_name text,
  action text not null,
  work_id bigint,
  project_name text,
  work_name text,
  target_staff_id uuid,
  target_name text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.activity_logs enable row level security;

drop policy if exists "Users can read own activity" on public.activity_logs;
create policy "Users can read own activity"
on public.activity_logs
for select
to authenticated
using (public.my_role() = 'admin' or actor_id = auth.uid());

drop policy if exists "System can insert activity" on public.activity_logs;
create policy "System can insert activity"
on public.activity_logs
for insert
to authenticated
with check (actor_id = auth.uid());

create or replace function public.activity_actor_name()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select name from public.profiles where id = auth.uid()), 'System');
$$;

create or replace function public.log_work_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  who text := public.activity_actor_name();
begin
  if tg_op = 'INSERT' then
    insert into public.activity_logs(actor_id,actor_name,action,work_id,project_name,work_name,target_staff_id,target_name,details)
    values(auth.uid(),who,'WORK_CREATED',new.id,new.project_name,new.work_name,new.assigned_to,
           (select name from public.profiles where id=new.assigned_to),
           jsonb_build_object('status',new.status));
    return new;
  elsif tg_op = 'UPDATE' then
    if (old.project_name,old.work_name) is distinct from (new.project_name,new.work_name) then
      insert into public.activity_logs(actor_id,actor_name,action,work_id,project_name,work_name,target_staff_id,target_name,details)
      values(auth.uid(),who,'WORK_EDITED',new.id,new.project_name,new.work_name,new.assigned_to,
             (select name from public.profiles where id=new.assigned_to),
             jsonb_build_object('old_project',old.project_name,'old_work',old.work_name));
    end if;
    if old.assigned_to is distinct from new.assigned_to then
      insert into public.activity_logs(actor_id,actor_name,action,work_id,project_name,work_name,target_staff_id,target_name,details)
      values(auth.uid(),who,'WORK_ASSIGNED',new.id,new.project_name,new.work_name,new.assigned_to,
             (select name from public.profiles where id=new.assigned_to),
             jsonb_build_object('from_staff',old.assigned_to,'to_staff',new.assigned_to));
    end if;
    if old.status is distinct from new.status or old.completion_type is distinct from new.completion_type or old.hdd_name is distinct from new.hdd_name then
      insert into public.activity_logs(actor_id,actor_name,action,work_id,project_name,work_name,target_staff_id,target_name,details)
      values(auth.uid(),who,
             case when new.status='completed' and new.completion_type='partial' then 'WORK_PARTIALLY_COMPLETED'
                  when new.status='completed' and new.completion_type='completed' then 'WORK_COMPLETED'
                  else 'WORK_UPDATED' end,
             new.id,new.project_name,new.work_name,new.assigned_to,
             (select name from public.profiles where id=new.assigned_to),
             jsonb_build_object('from_status',old.status,'to_status',new.status,'completion_type',new.completion_type,'hdd_name',new.hdd_name));
    end if;
    return new;
  else
    insert into public.activity_logs(actor_id,actor_name,action,work_id,project_name,work_name,target_staff_id,target_name,details)
    values(auth.uid(),who,'WORK_DELETED',old.id,old.project_name,old.work_name,old.assigned_to,
           (select name from public.profiles where id=old.assigned_to), '{}'::jsonb);
    return old;
  end if;
end;
$$;

drop trigger if exists works_activity_trigger on public.works;
create trigger works_activity_trigger
after insert or update or delete on public.works
for each row execute function public.log_work_activity();

create or replace function public.log_note_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.activity_logs(actor_id,actor_name,action,work_id,project_name,work_name,target_staff_id,target_name,details)
  select auth.uid(),public.activity_actor_name(),'PROGRESS_UPDATE_ADDED',w.id,w.project_name,w.work_name,w.assigned_to,
         (select name from public.profiles where id=w.assigned_to),
         jsonb_build_object('note',new.note,'hdd_name',coalesce(w.hdd_name,''))
  from public.works w where w.id=new.work_id;
  return new;
end;
$$;

drop trigger if exists work_notes_activity_trigger on public.work_notes;
create trigger work_notes_activity_trigger
after insert on public.work_notes
for each row execute function public.log_note_activity();

create or replace function public.log_profile_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  who text := public.activity_actor_name();
begin
  if tg_op='INSERT' then
    insert into public.activity_logs(actor_id,actor_name,action,target_staff_id,target_name,details)
    values(auth.uid(),who,'STAFF_ADDED',new.id,new.name,jsonb_build_object('username',new.username));
    return new;
  elsif tg_op='UPDATE' then
    if old.active is distinct from new.active then
      insert into public.activity_logs(actor_id,actor_name,action,target_staff_id,target_name,details)
      values(auth.uid(),who,case when new.active then 'STAFF_ACTIVATED' else 'STAFF_DEACTIVATED' end,new.id,new.name,jsonb_build_object('username',new.username));
    end if;
    return new;
  else
    insert into public.activity_logs(actor_id,actor_name,action,target_staff_id,target_name,details)
    values(auth.uid(),who,'STAFF_DELETED',old.id,old.name,jsonb_build_object('username',old.username));
    return old;
  end if;
end;
$$;

drop trigger if exists profiles_activity_trigger on public.profiles;
create trigger profiles_activity_trigger
after insert or update or delete on public.profiles
for each row execute function public.log_profile_activity();
